(function(g){var window=this;var Fua=function(a,b){var c=[];g.om(b,function(a){var b;try{b=g.MD.prototype.o.call(this,a,!0)}catch(f){if("Storage: Invalid value was encountered"==f)return;throw f;}g.p(b)?g.LD(b)&&c.push(a):c.push(a)},a);
return c},Gua=function(a,b){var c=Fua(a,b);
(0,g.F)(c,function(a){g.MD.prototype.remove.call(this,a)},a)},o9=function(a,b){g.lW.call(this,g.U("YTP_MDX_TITLE"),0,a,b);
this.W=a;this.B=!1;this.G={};this.V(a,"onMdxReceiversChange",this.H);this.V(a,"presentingplayerstatechange",this.H);this.H()},Hua=function(a){return a.H?a.F+((0,g.E)()-a.A)/1E3:a.F},Iua=function(){var a=g.oH;
Gua(a,a.g.Od(!0))},p9=function(a){g.RH.call(this,"ScreenServiceProxy");
this.Uc=a;this.o=[];this.o.push(this.Uc.$_s("screenChange",(0,g.z)(this.WP,this)));this.o.push(this.Uc.$_s("onlineScreenChange",(0,g.z)(this.sM,this)))},q9=function(a){g.EH("cloudview",a)},Jua=function(a){q9("setApiReady_ "+a);
g.t("yt.mdx.remote.cloudview.apiReady_",a,void 0)},r9=function(){return g.u("yt.mdx.remote.cloudview.instance_")},Kua=function(a){g.IG[a]&&(a=g.IG[a],(0,g.F)(a,function(a){g.GG[a]&&delete g.GG[a]}),a.length=0)},s9=function(){return g.u("yt.mdx.remote.connection_")},t9=function(a){g.t("yt.mdx.remote.connectData_",a,void 0)},Lua=function(a){g.t("yt.mdx.remote.currentScreenId_",a,void 0)},u9=function(){return g.u("yt.mdx.remote.currentScreenId_")},w9=function(){if(!v9){var a=g.u("yt.mdx.remote.screenService_");
v9=a?new p9(a):null}return v9},x9=function(a){g.t("yt.mdx.remote.cloudview.initializing_",a,void 0)},y9=function(){return!!g.u("yt.mdx.remote.cloudview.apiReady_")},z9=function(a){q9("setCastInstalled_ "+a);
g.qH("yt-remote-cast-installed",a)},A9=function(a){g.EH("cloudview",a)},Mua=function(a,b){r9().init(a,b)},B9=function(){return!!g.rH("yt-remote-cast-installed")},Nua=function(){q9("dispose");
var a=r9();a&&a.dispose();g.t("yt.mdx.remote.cloudview.instance_",null,void 0);Jua(!1);g.KG(C9);C9.length=0},Oua=function(){var a=window.document.createElement("a");
g.Rd(a,"https://www.gstatic.com/cv/js/sender/v1/cast_sender.js");a=a.href.replace(/^[a-zA-Z]+:\/\//,"//");return"js-"+g.Ua(a)},Pua=function(a,b){var c=window.document.createElement("script");
c.id=a;c.onload=function(){b&&(0,window.setTimeout)(b,0)};
c.onreadystatechange=function(){switch(c.readyState){case "loaded":case "complete":c.onload()}};
c.src="https://www.gstatic.com/cv/js/sender/v1/cast_sender.js";var d=window.document.getElementsByTagName("head")[0]||window.document.body;d.insertBefore(c,d.firstChild);return c},Qua=function(a){var b=g.EG();
if(b)if(b.clear(a),a)Kua(a);else for(var c in g.IG)Kua(c)},D9=function(){return g.u("yt.mdx.remote.channelParams_")||{}},F9=function(a){var b=s9();
t9(null);a||Lua("");g.t("yt.mdx.remote.connection_",a,void 0);E9&&((0,g.F)(E9,function(b){b(a)}),E9.length=0);
b&&!a?g.NG("yt-remote-connection-change",!1):!b&&a&&g.NG("yt-remote-connection-change",!0)},Rua=function(){return g.u("yt.mdx.remote.connectData_")},G9=function(){var a=u9();
if(!a)return null;var b=w9().Td();return g.QH(b,a)},Sua=function(a,b){z9(!0);
x9(!1);Mua(a,function(a){a?(Jua(!0),g.MG("yt-remote-cast2-api-ready")):(A9("Failed to initialize cast API."),z9(!1),g.sH("yt-remote-cast-available"),g.sH("yt-remote-cast-receiver"),Nua());b(a)})},Tua=function(){return B9()?r9()?r9().getCastSession():(A9("getCastSelector: Cast is not initialized."),null):(A9("getCastSelector: Cast API is not installed!"),null)},Uua=function(){var a=Oua(),b=window.document.getElementById(a),c=b&&g.DF(b,"loaded");
c||b&&!c||(b=Pua(a,function(){g.DF(b,"loaded")||(g.EF(b,"loaded","true"),g.MG(a),g.WE(g.za(Qua,a),0))}))},Vua=function(a){return(0,g.H)(a,function(a){return{key:a.id,
name:a.name}})},Wua=function(){if(g.poa){var a=2,b=g.Fh(),c=function(){a--;
0==a&&b&&b(!0)};
window.__onGCastApiAvailable=c;g.Kh("//www.gstatic.com/cast/sdk/libs/sender/1.0/cast_framework.js",g.Hh,c)}},I9=function(a,b){u9();
G9()&&G9();Lua(a.id);var c=new g.VI(H9,a,D9());c.connect(b,Rua());c.subscribe("beforeDisconnect",function(a){g.NG("yt-remote-before-disconnect",a)});
c.subscribe("beforeDispose",function(){s9()&&(s9(),F9(null))});
F9(c)},J9=function(){var a=g.WH();
if(!a)return null;var b=w9().Td();return g.QH(b,a)},K9=function(a){g.EH("remote",a)},L9=function(){var a=s9();
return!!a&&3!=a.getProxyState()},M9=function(){y9()?r9().stopSession():A9("stopSession called before API ready.");
var a=s9();a&&(a.disconnect(1),F9(null))},Xua=function(){var a;
a=w9().Uc.$_gos();var b=G9();b&&s9()&&(g.PH(a,b)||a.push(b));return Vua(a)},O9=function(a,b){g.gG.call(this);
this.g=0;this.B=a;this.D=[];this.C=new g.$B;this.A=this.o=null;this.H=(0,g.z)(this.CK,this);this.F=(0,g.z)(this.xk,this);this.G=(0,g.z)(this.BK,this);this.J=(0,g.z)(this.PK,this);var c=0;a?(c=a.getProxyState(),3!=c&&(a.subscribe("proxyStateChange",this.Js,this),Yua(this))):c=3;0!=c&&(b?this.Js(c):g.WE((0,g.z)(function(){this.Js(c)},this),0));
var d=Tua();d&&N9(this,d);this.subscribe("yt-remote-cast2-session-change",this.J)},P9=function(a){return new g.KI(a.B.getPlayerContextData())},Zua=function(a,b,c,d,e){var f=P9(a),k=e||f.listId;
d=d||0;var l={videoId:b,currentIndex:d};g.OI(f,b,d);g.p(c)&&(g.MI(f,c),l.currentTime=c);g.p(k)&&(l.listId=k);Q9(a,"setPlaylist",l);e||R9(a,f)},Yua=function(a){(0,g.F)("nowAutoplaying autoplayDismissed remotePlayerChange remoteQueueChange autoplayModeChange autoplayUpNext previousNextChange".split(" "),function(a){this.D.push(this.B.subscribe(a,g.za(this.LM,a),this))},a)},$ua=function(a){(0,g.F)(a.D,function(a){this.B.unsubscribeByKey(a)},a);
a.D.length=0},S9=function(a,b){50>a.C.Cc()&&g.bC(a.C,b)},T9=function(a,b,c){var d=P9(a);
g.MI(d,c);-1E3!=d.g&&(d.g=b);R9(a,d)},Q9=function(a,b,c){a.B.sendMessage(b,c)},R9=function(a,b){$ua(a);
a.B.setPlayerContextData(g.PI(b));Yua(a)},N9=function(a,b){a.A&&(a.A.removeUpdateListener(a.H),a.A.removeMediaListener(a.F),a.xk(null));
a.A=b;a.A&&(U9("Setting cast session: "+a.A.sessionId),a.A.addUpdateListener(a.H),a.A.addMediaListener(a.F),a.A.media.length&&a.xk(a.A.media[0]))},ava=function(a){var b=a.o.media,c=a.o.customData;
if(b&&c){var d=P9(a);b.contentId!=d.videoId&&U9("Cast changing video to: "+b.contentId);d.videoId=b.contentId;d.g=c.playerState;g.MI(d,a.o.getEstimatedTime());R9(a,d)}else U9("No cast media video. Ignoring state update.")},U9=function(a){g.EH("CP",a)},V9=function(a,b,c){return(0,g.z)(function(a){this.Yb("Failed to "+b+" with cast v2 channel. Error code: "+a.code);
a.code!=window.chrome.cast.ErrorCode.TIMEOUT&&(this.Yb("Retrying "+b+" using MDx browser channel."),Q9(this,b,c))},a)},bva=function(a){var b=!1;
r9()||(a=new g.EI(a),a.subscribe("yt-remote-cast2-availability-change",function(a){g.qH("yt-remote-cast-available",a);g.NG("yt-remote-cast2-availability-change",a)}),a.subscribe("yt-remote-cast2-receiver-selected",function(a){q9("onReceiverSelected: "+a.friendlyName);
g.qH("yt-remote-cast-receiver",a);g.NG("yt-remote-cast2-receiver-selected",a)}),a.subscribe("yt-remote-cast2-receiver-resumed",function(a){q9("onReceiverResumed: "+a.friendlyName);
g.qH("yt-remote-cast-receiver",a)}),a.subscribe("yt-remote-cast2-session-change",function(a){q9("onSessionChange: "+g.MH(a));
a||g.sH("yt-remote-cast-receiver");g.NG("yt-remote-cast2-session-change",a)}),g.t("yt.mdx.remote.cloudview.instance_",a,void 0),b=!0);
q9("cloudview.createSingleton_: "+b);return b},cva=function(){var a=0<=g.Hb.search(/\ (CrMo|Chrome|CriOS)\//);
return g.vG||a},W9=function(a,b){y9()?r9().setConnectedScreenStatus(a,b):A9("setConnectedScreenStatus called before ready.")},dva=function(){q9("clearCurrentReceiver");
g.sH("yt-remote-cast-receiver")},eva=function(){if(0<=window.navigator.userAgent.indexOf("CriOS")){var a=window.__gCrWeb&&window.__gCrWeb.message&&window.__gCrWeb.message.invokeOnHost;
if(a){Wua();a({command:"cast.sender.init"});return}}if(window.chrome)if(Wua(),a=window.navigator.userAgent,0<=a.indexOf("Android")&&0<=a.indexOf("Chrome/")&&window.navigator.presentation){var a="",b=g.Dh();55<=b?a="55":50<=b&&(a="50");g.Kh("//www.gstatic.com/eureka/clank"+a+g.Ih,g.Hh)}else g.Lh(0);else g.Hh()},fva=function(a){a?(g.qH("yt-remote-session-app",a.app),g.qH("yt-remote-session-name",a.name)):(g.sH("yt-remote-session-app"),g.sH("yt-remote-session-name"));
g.t("yt.mdx.remote.channelParams_",a,void 0)},gva=function(){var a=D9();
if(g.Vb(a)){var a=g.VH(),b=g.rH("yt-remote-session-name")||"",c=g.rH("yt-remote-session-app")||"",a={device:"REMOTE_CONTROL",id:a,name:b,app:c,"mdx-version":3};g.t("yt.mdx.remote.channelParams_",a,void 0)}},hva=function(){var a=J9();
a?(K9("Resume connection to: "+g.MH(a)),I9(a,0)):(g.dI(),dva(),K9("Skipping connecting because no session screen found."))},iva=function(a){K9("remote.onCastSessionChange_: "+g.MH(a));
if(a){var b=G9();b&&b.id==a.id?W9(b.id,"YouTube TV"):(b&&M9(),I9(a,1))}else s9()&&M9()},jva=function(){var a=Xua(),b=G9();
b||(b=J9());return g.bb(a,function(a){return b&&g.JH(b,a.key)?!0:!1})},kva=function(){var a=g.rH("yt-remote-cast-receiver");
return a?a.friendlyName:null},lva=function(a,b,c,d){cva()?bva(b)&&(x9(!0),window.chrome&&window.chrome.cast&&window.chrome.cast.isAvailable?Sua(a,c):(window.__onGCastApiAvailable=function(b,d){b?Sua(a,c):(A9("Failed to load cast API: "+d),z9(!1),x9(!1),g.sH("yt-remote-cast-available"),g.sH("yt-remote-cast-receiver"),Nua(),c(!1))},d?window.spf?window.spf.script.load("https://www.gstatic.com/cv/js/sender/v1/cast_sender.js","",void 0):Uua():eva())):q9("Cannot initialize because not running Chrome")},
mva=function(a){this.port=this.A="";
this.g="/api/lounge";this.o=!0;a=a||window.document.location.href;var b=g.yg(a)||"";b&&(this.port=":"+b);this.A=g.xg(a)||"";a=g.Hb;0<=a.search("MSIE")&&(a=a.match(/MSIE ([\d.]+)/)[1],0>g.Ta(a,"10.0")&&(this.o=!1))},X9=function(a){g.X.call(this,{K:"div",
X:"ytp-remote",R:[{K:"div",X:"ytp-remote-display-status",R:[{K:"div",X:"ytp-remote-display-status-icon",R:[g.sE()]},{K:"div",X:"ytp-remote-display-status-text",R:["{{statustext}}"]},{K:"div",X:"ytp-remote-display-status-receiver",R:["{{receiver}}"]}]}]});this.g=new g.MV(this,250);g.M(this,this.g);this.A=a;this.V(a,"presentingplayerstatechange",this.B);nva(this,g.lV(a))},nva=function(a,b){if(3==a.A.Xa()){var c;
c=g.V(b,128)?g.U("YTP_MDX_STATUS_ERROR"):b.qb()||g.V(b,4)?g.U("YTP_MDX_STATUS_PLAYING"):g.U("YTP_MDX_STATUS_CONNECTED");var d=a.A.Wc("remote","currentReceiver");a.update({statustext:c,receiver:d.name});a.g.show()}else g.OV(a.g)},Y9=function(a,b,c){g.L.call(this);
this.H=a;this.W=b;b.addEventListener("onVolumeChange",this.mn,this);b.addEventListener("onCaptionsTrackListChanged",this.Ky,this);b.addEventListener("captionschanged",this.yy,this);b.addEventListener("captionssettingschanged",this.Wr,this);b.addEventListener("videoplayerreset",this.Ak,this);b.addEventListener("mdxautoplaycancel",this.yu,this);this.C=!1;this.g=c;c.subscribe("proxyStateChange",this.Xy,this);c.subscribe("remotePlayerChange",this.zk,this);c.subscribe("remoteQueueChange",this.Ak,this);
c.subscribe("autoplayUpNext",this.vy,this);c.subscribe("previousNextChange",this.Uy,this);c.subscribe("nowAutoplaying",this.Ny,this);c.subscribe("autoplayDismissed",this.uy,this);this.suggestion=null;this.D=new g.YJ(64);this.o=new g.ku(this.kA,500,this);g.M(this,this.o);this.A=new g.ku(this.lA,1E3,this);g.M(this,this.A);this.B={};this.G=new g.ku(this.zA,1E3,this);g.M(this,this.G);this.F=new g.tk(this.RR,1E3,this);g.M(this,this.F);this.J=g.x;this.Wr();this.Ak();this.zk()},Z9=function(a,b){var c=a.H,
d=a.W.getVideoData().lengthSeconds;
c.H=b||0;c.g.U("progresssync",b,d)},ova=function(a){Z9(a,0);
a.o.stop();$9(a,new g.YJ(64))},c$=function(a,b){if(a$(a)&&!a.C){var c=null;
b&&(c={style:a.W.bl()},g.bc(c,b));a.g.eA(b$(a),c);a.B=P9(a.g).o}},d$=function(a,b){var c=a.W.bf();
c?Zua(a.g,b$(a),b,c.Rd(),c.listId.toString()):Zua(a.g,b$(a),b);$9(a,new g.YJ(1))},pva=function(a,b){if(b){var c=a.W.Wc("captions","tracklist",{Ow:1});
c&&c.length?(a.W.Ee("captions","track",b),a.C=!1):(a.W.Xk("captions"),a.C=!0)}else a.W.Ee("captions","track",{})},a$=function(a){return P9(a.g).videoId==b$(a)},b$=function(a){return a.W.getVideoData().videoId},$9=function(a,b){a.A.stop();
var c=a.D;if(b.o!=c.o||b.g!=c.g){var d=g.V(b,2);if(d!=g.V(a.D,2)){var e=a.W;(e=g.kV(e.app,e.playerType||1))&&g.iU(e,d)}a.D=b;qva(a.H,c,b)}},e$=function(){var a=jva();
!a&&B9()&&kva()&&(a={key:"cast-selector-receiver",name:kva()});return a},rva=function(){var a=Xua();
B9()&&g.rH("yt-remote-cast-available")&&a.push({key:"cast-selector-receiver",name:"Cast..."});return a},sva=function(a){var b={device:"Desktop",
app:"youtube-desktop"};g.oH&&Iua();g.YH();H9||(H9=new mva,g.fI()&&(H9.g="/api/loungedev"));E9||(E9=g.u("yt.mdx.remote.deferredProxies_")||[],g.t("yt.mdx.remote.deferredProxies_",E9,void 0));gva();var c=w9();if(!c){var d=new g.qI(H9);g.t("yt.mdx.remote.screenService_",d,void 0);c=w9();lva(a,d,function(a){a?u9()&&W9(u9(),"YouTube TV"):d.subscribe("onlineScreenChange",function(){g.NG("yt-remote-receiver-availability-change")})},!(!b||!b.loadCastApiSetupScript))}b&&!g.u("yt.mdx.remote.initialized_")&&
(g.t("yt.mdx.remote.initialized_",!0,void 0),K9("Initializing: "+g.Mc(b)),f$.push(g.JG("yt-remote-cast2-availability-change",function(){g.NG("yt-remote-receiver-availability-change")})),f$.push(g.JG("yt-remote-cast2-receiver-selected",function(){t9(null);
g.NG("yt-remote-auto-connect","cast-selector-receiver")})),f$.push(g.JG("yt-remote-cast2-receiver-resumed",function(){g.NG("yt-remote-receiver-resumed","cast-selector-receiver")})),f$.push(g.JG("yt-remote-cast2-session-change",iva)),f$.push(g.JG("yt-remote-connection-change",function(a){a?W9(u9(),"YouTube TV"):J9()||(W9(null,null),dva())})),a=D9(),b.isAuto&&(a.id+="#dial"),g.mG("desktop_enable_autoplay")&&(a.capabilities=["atp"]),a.name=b.device,a.app=b.app,K9(" -- with channel params: "+g.Mc(a)),
fva(a),c.start(),u9()||hva())},g$=function(){B9()?r9()?y9()?(q9("Requesting cast selector."),r9().requestSession()):(q9("Wait for cast API to be ready to request the session."),C9.push(g.JG("yt-remote-cast2-api-ready",g$))):A9("requestCastSelector: Cast is not initialized."):A9("requestCastSelector: Cast API is not installed!")},h$=function(a){g.IV.call(this,a);
this.A={key:g.OH(),name:g.U("YTP_MDX_MY_COMPUTER")};this.C=null;this.D=[];this.J=this.o=null;this.G=[this.A];this.B=this.A;this.F=new g.YJ(64);this.H=0;var b=g.eV(a).C;b&&(b=b.A&&b.A.g)&&(b=new o9(a,b),g.M(this,b));b=new X9(a);g.M(this,b);g.CV(a,b.element,5)},qva=function(a,b,c){a.F=c;
a.g.U("presentingplayerstatechange",new g.aU(c,b))},i$=function(a,b){if(b.key!=a.B.key)if(b.key==a.A.key)M9();
else{a.B=b;var c;c=a.g.getPlaylistId();var d=a.g.getVideoData().videoId;if(c||d){var e,f=a.g.bf();if(f){e=[];for(var k=0;k<f.getLength();k++)e[k]=f.Wb(k).videoId}else e=[a.g.getVideoData().videoId];c={videoIds:e,listId:c,videoId:d,index:Math.max(a.g.VA(),0),currentTime:a.g.getCurrentTime()}}else c=null;K9("Connecting to: "+g.Mc(b));"cast-selector-receiver"==b.key?(t9(c||null),c=c||null,y9()?r9().setLaunchParams(c):A9("setLaunchParams called before ready.")):!c&&L9()&&u9()==b.key?g.NG("yt-remote-connection-change",
!0):(M9(),t9(c||null),c=w9().Td(),(c=g.QH(c,b.key))&&I9(c,1))}};
g.ca(o9,g.lW);o9.prototype.H=function(){var a=this.W.Wc("remote","receivers");a&&1<a.length&&!this.W.Wc("remote","quickCast")?(this.G=g.Db(a,this.F,this),g.nW(this,(0,g.H)(a,this.F)),a=this.W.Wc("remote","currentReceiver"),g.mW(this,this.F(a)),this.B||(g.u1(this.g,this),this.B=!0)):this.B&&(g.v1(this.g,this),this.B=!1)};
o9.prototype.F=function(a){return a.key};
o9.prototype.Me=function(a){return"cast-selector-receiver"==a?g.U("YTP_MDX_CAST_SELECTOR"):this.G[a].name};
o9.prototype.hd=function(a){g.lW.prototype.hd.call(this,a);this.W.Ee("remote","currentReceiver",this.G[a]);this.g.Tb()};
g.A(p9,g.RH);g.h=p9.prototype;g.h.Td=function(a){return this.Uc.$_gs(a)};
g.h.contains=function(a){return!!this.Uc.$_c(a)};
g.h.get=function(a){return this.Uc.$_g(a)};
g.h.start=function(){this.Uc.$_st()};
g.h.ho=function(a,b,c){this.Uc.$_a(a,b,c)};
g.h.remove=function(a,b,c){this.Uc.$_r(a,b,c)};
g.h.Tn=function(a,b,c,d){this.Uc.$_un(a,b,c,d)};
g.h.P=function(){for(var a=0,b=this.o.length;a<b;++a)this.Uc.$_ubk(this.o[a]);this.o.length=0;this.Uc=null;p9.O.P.call(this)};
g.h.WP=function(){this.U("screenChange")};
g.h.sM=function(){this.U("onlineScreenChange")};
var v9=null,C9=[],E9=null,H9=null;g.A(O9,g.gG);g.h=O9.prototype;g.h.play=function(){1==this.g?(this.o?this.o.play(null,g.x,V9(this,"play")):Q9(this,"play"),T9(this,1,g.NI(P9(this))),this.U("remotePlayerChange")):S9(this,this.play)};
g.h.pause=function(){1==this.g?(this.o?this.o.pause(null,g.x,V9(this,"pause")):Q9(this,"pause"),T9(this,2,g.NI(P9(this))),this.U("remotePlayerChange")):S9(this,this.pause)};
g.h.KA=function(a){if(1==this.g){if(this.o){var b=P9(this),c=new window.chrome.cast.media.SeekRequest;c.currentTime=a;c.resumeState=b.qb()||3==b.g?window.chrome.cast.media.ResumeState.PLAYBACK_START:window.chrome.cast.media.ResumeState.PLAYBACK_PAUSE;this.o.seek(c,g.x,V9(this,"seekTo",{newTime:a}))}else Q9(this,"seekTo",{newTime:a});T9(this,3,a);this.U("remotePlayerChange")}else S9(this,g.za(this.KA,a))};
g.h.stop=function(){if(1==this.g){this.o?this.o.stop(null,g.x,V9(this,"stopVideo")):Q9(this,"stopVideo");var a=P9(this);a.index=-1;a.videoId="";g.LI(a);R9(this,a);this.U("remotePlayerChange")}else S9(this,this.stop)};
g.h.setVolume=function(a,b){if(1==this.g){var c=P9(this);if(this.A){if(c.volume!=a){var d=Math.round(a)/100;this.A.setReceiverVolumeLevel(d,(0,g.z)(function(){U9("set receiver volume: "+d)},this),(0,g.z)(function(){this.Yb("failed to set receiver volume.")},this))}c.muted!=b&&this.A.setReceiverMuted(b,(0,g.z)(function(){U9("set receiver muted: "+b)},this),(0,g.z)(function(){this.Yb("failed to set receiver muted.")},this))}else{var e={volume:a,
muted:b};-1!=c.volume&&(e.delta=a-c.volume);Q9(this,"setVolume",e)}c.muted=b;c.volume=a;R9(this,c)}else S9(this,g.za(this.setVolume,a,b))};
g.h.eA=function(a,b){if(1==this.g){var c=P9(this),d={videoId:a};b&&(c.o={trackName:b.name,languageCode:b.languageCode,sourceLanguageCode:b.translationLanguage?b.translationLanguage.languageCode:"",languageName:b.languageName,format:b.format,kind:b.kind},d.style=g.Mc(b.style),g.bc(d,c.o));Q9(this,"setSubtitlesTrack",d);R9(this,c)}else S9(this,g.za(this.eA,a,b))};
g.h.Is=function(a,b){if(1==this.g){Q9(this,"setAudioTrack",{videoId:a,audioTrackId:b.Kc.id});var c=P9(this);c.audioTrackId=b.Kc.id;R9(this,c)}else S9(this,g.za(this.Is,a,b))};
g.h.JA=function(a,b){if(1==this.g){if(a&&b){var c=P9(this);g.OI(c,a,b);R9(this,c)}Q9(this,"previous")}else S9(this,g.za(this.JA,a,b))};
g.h.IA=function(a,b){if(1==this.g){if(a&&b){var c=P9(this);g.OI(c,a,b);R9(this,c)}Q9(this,"next")}else S9(this,g.za(this.IA,a,b))};
g.h.gv=function(){1==this.g?Q9(this,"dismissAutoplay"):S9(this,this.gv)};
g.h.dispose=function(){if(3!=this.g){var a=this.g;this.g=3;this.U("proxyStateChange",a,this.g)}O9.O.dispose.call(this)};
g.h.P=function(){$ua(this);this.B=null;this.C.clear();N9(this,null);O9.O.P.call(this)};
g.h.Js=function(a){if((a!=this.g||2==a)&&3!=this.g&&0!=a){var b=this.g;this.g=a;this.U("proxyStateChange",b,a);if(1==a)for(;!this.C.isEmpty();)g.cC(this.C).apply(this);else 3==a&&this.dispose()}};
g.h.LM=function(a,b){this.U(a,b)};
g.h.CK=function(a){if(!a)this.xk(null),N9(this,null);else if(this.A.receiver.volume){a=this.A.receiver.volume;var b=P9(this),c=Math.round(100*a.level||0);if(b.volume!=c||b.muted!=a.muted)U9("Cast volume update: "+a.level+(a.muted?" muted":"")),b.volume=c,b.muted=!!a.muted,R9(this,b)}};
g.h.xk=function(a){U9("Cast media: "+!!a);this.o&&this.o.removeUpdateListener(this.G);if(this.o=a)this.o.addUpdateListener(this.G),ava(this),this.U("remotePlayerChange")};
g.h.BK=function(a){a?(ava(this),this.U("remotePlayerChange")):this.xk(null)};
g.h.PK=function(){var a=Tua();a&&N9(this,a)};
g.h.Yb=function(a){g.EH("CP",a)};
var f$=[];g.h=mva.prototype;g.h.Eh=function(a,b,c){var d=this.g;if(g.p(c)?c:this.o)d="https://"+this.A+this.port+this.g;return g.Gg(d+a,b||{})};
g.h.Hs=function(a,b,c,d){c={format:"JSON",method:"POST",context:this,timeout:5E3,withCredentials:!1,Jb:g.za(this.RP,c,!0),onError:g.za(this.QP,d),gd:g.za(this.SP,d)};b&&(c.Nb=b,c.headers={"Content-Type":"application/x-www-form-urlencoded"});return g.iF(a,c)};
g.h.RP=function(a,b,c,d){b?a(d):a({text:c.responseText})};
g.h.QP=function(a,b){a(Error("Request error: "+b.status))};
g.h.SP=function(a){a(Error("request timed out"))};
g.ca(X9,g.X);X9.prototype.B=function(a){nva(this,a.state)};
g.A(Y9,g.L);g.h=Y9.prototype;
g.h.P=function(){Y9.O.P.call(this);this.o.stop();this.A.stop();this.J();this.W.removeEventListener("onVolumeChange",this.mn,this);this.W.removeEventListener("onCaptionsTrackListChanged",this.Ky,this);this.W.removeEventListener("captionschanged",this.yy,this);this.W.removeEventListener("videoplayerreset",this.Ak,this);this.W.removeEventListener("captionssettingschanged",this.Wr,this);this.W.removeEventListener("mdxautoplaycancel",this.yu,this);this.g.unsubscribe("proxyStateChange",this.Xy,this);this.g.unsubscribe("remotePlayerChange",
this.zk,this);this.g.unsubscribe("remoteQueueChange",this.Ak,this);this.g.unsubscribe("autoplayUpNext",this.vy,this);this.g.unsubscribe("previousNextChange",this.Uy,this);this.g.unsubscribe("nowAutoplaying",this.Ny,this);this.g.unsubscribe("autoplayDismissed",this.uy,this);this.g=this.H=null};
g.h.yB=function(a,b){2==this.g.g||(a$(this)?this.tG.apply(this,arguments):this.pG.apply(this,arguments))};
g.h.yy=function(a){this.yB("control_subtitles_set_track",g.Vb(a)?null:a)};
g.h.Wr=function(){var a=this.W.Wc("captions","track");g.Vb(a)||c$(this,a)};
g.h.pG=function(a,b){var c=Array.prototype.slice.call(arguments,1);switch(a){case "control_toggle_play_pause":case "control_play":case "control_pause":d$(this,this.W.getCurrentTime());break;case "control_seek":d$(this,c[0]);break;case "control_subtitles_set_track":c$(this,c[0]);break;case "control_set_audio_track":c=c[0],a$(this)&&this.g.Is(b$(this),c)}};
g.h.tG=function(a,b){if(1081!=P9(this.g).g||"control_seek"!=a){var c=Array.prototype.slice.call(arguments,1);switch(a){case "control_toggle_play_pause":P9(this.g).qb()?this.g.pause():this.g.play();break;case "control_play":this.g.play();break;case "control_pause":this.g.pause();break;case "control_seek":this.F.Ki(c[0],c[1]);break;case "control_subtitles_set_track":c$(this,c[0]);break;case "control_set_audio_track":c=c[0],a$(this)&&this.g.Is(b$(this),c)}}};
g.h.mn=function(a){if(a$(this)){this.g.unsubscribe("remotePlayerChange",this.zk,this);var b=Math.round(a.volume);a=!!a.muted;var c=P9(this.g);if(b!=c.volume||a!=c.muted)this.g.setVolume(b,a),this.G.start();this.g.subscribe("remotePlayerChange",this.zk,this)}};
g.h.Ky=function(){g.Vb(this.B)||pva(this,this.B);this.C=!1};
g.h.Xy=function(a,b){this.A.stop();2==b&&this.lA()};
g.h.zk=function(){if(a$(this)){this.o.stop();var a=P9(this.g);switch(a.g){case 1081:$9(this,new g.YJ(8));break;case 1:this.kA();$9(this,new g.YJ(8));break;case 1083:case 3:$9(this,new g.YJ(9));break;case 0:$9(this,new g.YJ(2));this.F.stop();Z9(this,this.W.getVideoData().lengthSeconds);break;case 1082:$9(this,new g.YJ(4));break;case 2:$9(this,new g.YJ(4));Z9(this,g.NI(a));break;case -1:$9(this,new g.YJ(64));break;case -1E3:a={errorCode:"mdx.remoteerror",message:g.U("YTP_MDX_PLAYER_ERROR")},$9(this,
new g.YJ(128,a))}var a=P9(this.g).o,b=this.B;(a||b?a&&b&&a.trackName==b.trackName&&a.languageCode==b.languageCode&&a.languageName==b.languageName&&a.format==b.format&&a.kind==b.kind:1)||(this.B=a,pva(this,a));a=P9(this.g);-1==a.volume||Math.round(this.W.getVolume())==a.volume&&this.W.Zd()==a.muted||this.G.isActive()||this.zA()}else ova(this)};
g.h.Uy=function(){this.W.U("mdxpreviousnextchange")};
g.h.Ak=function(){a$(this)||ova(this)};
g.h.yu=function(){this.g.gv()};
g.h.vy=function(a){a&&(a=g.iF("/watch_queue_ajax",{method:"GET",Gc:{action_get_watch_queue_item:1,video_id:a},Jb:(0,g.z)(this.JN,this)}))&&(this.J=(0,g.z)(a.abort,a))};
g.h.JN=function(a,b){var c=new g.EQ({videoId:b.videoId,title:b.title,author:b.author,murlmq_webp:b.url});this.suggestion=c;this.W.U("mdxautoplayupnext",c)};
g.h.Ny=function(a){(0,window.isNaN)(a)||this.W.U("mdxnowautoplaying",a)};
g.h.uy=function(){this.W.U("mdxautoplaycanceled")};
g.h.RR=function(a,b){-1==P9(this.g).g?d$(this,a):b&&this.g.KA(a)};
g.h.zA=function(){if(a$(this)){var a=P9(this.g);this.W.removeEventListener("onVolumeChange",this.mn,this);a.muted?this.W.mute():this.W.wg();this.W.setVolume(a.volume);this.W.addEventListener("onVolumeChange",this.mn,this)}};
g.h.kA=function(){this.o.stop();if(!this.g.la()){var a=P9(this.g);a.qb()&&$9(this,new g.YJ(8));Z9(this,g.NI(a));this.o.start()}};
g.h.lA=function(){this.A.stop();this.o.stop();var a=this.g.B.getReconnectTimeout();2==this.g.g&&!(0,window.isNaN)(a)&&this.A.start()};
g.A(h$,g.IV);g.h=h$.prototype;g.h.create=function(){sva("embedded"==g.Y(this.g).g);this.D.push(g.JG("yt-remote-before-disconnect",this.yK,this));this.D.push(g.JG("yt-remote-connection-change",this.UM,this));this.D.push(g.JG("yt-remote-receiver-availability-change",this.Vy,this));this.D.push(g.JG("yt-remote-auto-connect",this.SM,this));this.D.push(g.JG("yt-remote-receiver-resumed",this.RM,this));this.Vy()};
g.h.load=function(){this.g.ip();h$.O.load.call(this);this.C=new Y9(this,this.g,this.o);var a;a=(a=Rua())?a.currentTime:0;var b=L9()?new O9(s9(),void 0):null;0==a&&b&&(a=g.NI(P9(b)));0!=a&&(this.H=a||0,this.g.U("progresssync",a,void 0));qva(this,this.F,this.F);g.y2(this.g.app,6)};
g.h.unload=function(){this.g.U("mdxautoplaycanceled");this.B=this.A;g.Ve(this.C,this.o);this.o=this.C=null;h$.O.unload.call(this);g.y2(this.g.app,5)};
g.h.P=function(){g.KG(this.D);h$.O.P.call(this)};
g.h.jl=function(a,b){this.loaded&&this.C.yB.apply(this.C,arguments)};
g.h.UF=function(){return this.loaded?this.C.suggestion:null};
g.h.zf=function(){return this.o?P9(this.o).zf:!1};
g.h.hasNext=function(){return this.o?P9(this.o).hasNext:!1};
g.h.getCurrentTime=function(){return this.H};
g.h.vR=function(){var a=P9(this.o),b=this.g.getVideoData(),c=this.g.Fd(),d=b.clipEnd,b=b.clipStart,e=this.getCurrentTime(),f=a.getDuration(),k;k=a.H?a.B+((0,g.E)()-a.A)/1E3:a.B;var l=1>=Hua(a)-this.getCurrentTime(),m=a.J,n=Hua(a),a=0<a.C?a.C+((0,g.E)()-a.A)/1E3:a.C;return{allowSeeking:c,clipEnd:d,clipStart:b,current:e,displayedStart:-1,duration:f,ingestionTime:k,isPeggedToLive:l,loaded:m,seekableEnd:n,seekableStart:a}};
g.h.wR=function(){this.o&&this.o.IA()};
g.h.xR=function(){this.o&&this.o.JA()};
g.h.yK=function(a){1==a&&(this.J=this.o?P9(this.o):null)};
g.h.UM=function(){var a=L9()?new O9(s9(),void 0):null;if(a){var b=this.B;this.loaded&&this.unload();this.o=a;this.J=null;b.key!=this.A.key&&(this.B=b,this.load())}else g.Ue(this.o),this.o=null,this.loaded&&(this.unload(),(a=this.J)&&a.videoId==this.g.getVideoData().videoId&&this.g.Qc(g.NI(a)));this.g.U("videodatachange","newdata",this.g.getVideoData(),3)};
g.h.Vy=function(){this.G=[this.A].concat(rva());var a=e$()||this.A;i$(this,a);this.g.xa("onMdxReceiversChange")};
g.h.SM=function(){var a=e$();i$(this,a)};
g.h.RM=function(){this.B=e$()};
g.h.uR=function(a,b){switch(a){case "casting":return this.loaded;case "receivers":return this.G;case "currentReceiver":return b&&("cast-selector-receiver"==b.key?g$():i$(this,b)),this.loaded?this.B:this.A;case "quickCast":return 2==this.G.length&&"cast-selector-receiver"==this.G[1].key?(b&&g$(),!0):!1}};
g.h.yR=function(){Q9(this.o,"sendDebugCommand",{debugCommand:"stats4nerds "})};
g.h.ye=function(){return!1};
window._exportCheck==g.Ca&&g.t("ytmod.player.remote",h$,void 0);})(_yt_player);
